#!/usr/bin/env bun

/**
 * Coding Agent Skill Generator
 *
 * Generates specialized coding agent skills based on:
 * - Detected project type
 * - Extracted codebase knowledge
 * - Tech stack
 */

import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { ExtractedKnowledge } from '../extractors/base-extractor.ts';

/**
 * Generate coding specialist agent skills
 */
export async function generateCodingAgentSkills(
  projectRoot: string,
  knowledge: ExtractedKnowledge
): Promise<void> {
  const agentsDir = join(projectRoot, '.claude', 'skills', 'coding-specialists');
  const agentsSubDir = join(agentsDir, 'agents');

  // Create directories
  if (!existsSync(agentsDir)) mkdirSync(agentsDir, { recursive: true });
  if (!existsSync(agentsSubDir)) mkdirSync(agentsSubDir, { recursive: true });

  // Generate router skill
  await generateRouterSkill(agentsDir, knowledge);

  // Generate language-specific coding agents
  if (knowledge.projectType.language === 'typescript' || knowledge.projectType.language === 'javascript') {
    await generateTypeScriptCodingAgent(agentsSubDir, knowledge);
  } else if (knowledge.projectType.language === 'python') {
    await generatePythonCodingAgent(agentsSubDir, knowledge);
  }

  // Generate database agent if database detected
  if (knowledge.databaseSchema) {
    await generateDatabaseCodingAgent(agentsSubDir, knowledge);
  }

  // Generate API agent if API routes detected
  if (knowledge.apiRoutes && knowledge.apiRoutes.length > 0) {
    await generateAPICodingAgent(agentsSubDir, knowledge);
  }

  // Generate test writing agent
  await generateTestWriterAgent(agentsSubDir, knowledge);

  console.log(`[agent-generator] ✅ Generated coding agent skills in ${agentsDir}`);
}

/**
 * Generate router skill (SKILL.md)
 */
async function generateRouterSkill(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const { language, framework } = knowledge.projectType;
  const projectName = knowledge.techStack.frameworks[0]?.name || language;

  const content = `---
name: coding-specialists
description: |
  Project-specific coding specialists for ${projectName}.
  USE WHEN implementing features, fixing bugs, or writing code.

  Router automatically selects the right specialist based on task keywords.
---

# Coding Specialists Router

This skill provides access to specialized coding agents with deep knowledge of this codebase.

## Available Specialists

### 1. Primary Coder
**Triggers**: "implement", "create", "build", "add feature"
**Expertise**: ${framework || language} development with project patterns

### 2. Database Coder
**Triggers**: "database", "query", "schema", "migration", "model"
**Expertise**: ${knowledge.databaseSchema?.orm || 'Database'} operations

### 3. API Coder
**Triggers**: "api", "endpoint", "route", "request", "response"
**Expertise**: API development and integration

### 4. Test Writer
**Triggers**: "test", "testing", "spec", "coverage"
**Expertise**: Test creation with ${knowledge.techStack.testing?.[0]?.framework || 'project testing framework'}

## How to Use

Simply describe your coding task. The router will:
1. Analyze keywords in your request
2. Select the appropriate specialist
3. Load relevant codebase knowledge
4. Display routing decision for transparency

## Routing Display

\`\`\`
╔═══════════════════════════════════════════╗
║ 🤖 AGENT ROUTING                          ║
╠═══════════════════════════════════════════╣
║ Task: Add user authentication             ║
║ Selected: api-coder                       ║
║ Reason: Matches API keywords              ║
║ Confidence: 95%                           ║
╚═══════════════════════════════════════════╝
\`\`\`

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'SKILL.md'), content);
}

/**
 * Generate TypeScript coding agent
 */
async function generateTypeScriptCodingAgent(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const framework = knowledge.projectType.framework || 'TypeScript';
  const frameworkName = knowledge.techStack.frameworks[0]?.name || framework;
  const isNextJS = framework === 'nextjs';
  const hasClerk = knowledge.apiRoutes?.some(r => r.auth) || false;

  const authPattern = hasClerk
    ? `\`\`\`typescript
import { auth } from '@clerk/nextjs';

export async function GET() {
  const { userId } = auth();
  if (!userId) {
    return new Response('Unauthorized', { status: 401 });
  }
  // ... rest of handler
}
\`\`\``
    : '// Auth patterns to be determined';

  const componentPattern = isNextJS
    ? `\`\`\`typescript
// Default: Server Component (no 'use client')
export default function MyComponent() {
  return <div>Server Component</div>;
}

// Client Component (only when needed)
'use client';

export default function InteractiveComponent() {
  const [state, setState] = useState();
  return <div>Client Component</div>;
}
\`\`\``
    : '// Component patterns to be determined';

  const content = `---
name: primary-coder
description: |
  ${frameworkName} coding specialist with deep project knowledge.
  USE WHEN implementing features, components, or ${framework} code.
---

# ${frameworkName} Coding Specialist

Expert in ${frameworkName} development following this project's patterns.

## Tech Stack Knowledge

**Framework**: ${frameworkName}
**Language**: TypeScript
${knowledge.techStack.database ? `**Database**: ${knowledge.techStack.database.orm}` : ''}
**Testing**: ${knowledge.techStack.testing?.[0]?.framework || 'To be configured'}

## Codebase Patterns

### Services
Load \`code-patterns.md\` skill for complete service list.

${knowledge.codePatterns.services && knowledge.codePatterns.services.length > 0
  ? `Example services available:
${knowledge.codePatterns.services.slice(0, 3).map(s => `- ${s.name}`).join('\n')}`
  : 'No service patterns detected yet.'}

### Components
${isNextJS ? 'Server Components by default, Client Components only when needed.' : 'Standard React component patterns.'}

${componentPattern}

${hasClerk ? `### Authentication Pattern
${authPattern}` : ''}

## Code Quality Rules

1. **Zero console.log statements** - Use structured logger
2. **TypeScript strict mode** - No 'any' types
3. **Error handling** - All catch blocks must have typed error params
4. **Testing** - Write tests for new features
5. **File size** - Max 300 lines per file

## Instructions

1. **ALWAYS** load \`tech-stack.md\` and \`code-patterns.md\` skills first
2. **FOLLOW** existing patterns found in codebase
3. **USE** correct imports and versions from tech stack
4. **IMPLEMENT** proper error handling with typed errors
5. **WRITE** tests for new code

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'primary-coder.md'), content);
}

/**
 * Generate Python coding agent
 */
async function generatePythonCodingAgent(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const framework = knowledge.projectType.framework || 'Python';
  const frameworkName = knowledge.techStack.frameworks[0]?.name || framework;

  const content = `---
name: primary-coder
description: |
  ${frameworkName} coding specialist with deep project knowledge.
  USE WHEN implementing features, services, or ${framework} code.
---

# ${frameworkName} Coding Specialist

Expert in ${frameworkName} development following this project's patterns.

## Tech Stack Knowledge

**Framework**: ${frameworkName}
**Language**: Python
${knowledge.techStack.database ? `**Database**: ${knowledge.techStack.database.orm}` : ''}
**Testing**: ${knowledge.techStack.testing?.[0]?.framework || 'pytest'}

## Codebase Patterns

Load \`code-patterns.md\` skill for complete service and model list.

## Code Quality Rules

1. **Type hints** - Use type annotations for all functions
2. **Docstrings** - Comprehensive documentation
3. **Testing** - pytest with >90% coverage
4. **Linting** - Black formatting, ruff for linting
5. **Error handling** - Proper exception handling

## Instructions

1. **ALWAYS** load \`tech-stack.md\` and \`code-patterns.md\` skills first
2. **FOLLOW** existing patterns found in codebase
3. **USE** correct imports and versions from tech stack
4. **IMPLEMENT** proper error handling
5. **WRITE** tests for new code

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'primary-coder.md'), content);
}

/**
 * Generate database coding agent
 */
async function generateDatabaseCodingAgent(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const orm = knowledge.databaseSchema?.orm || 'Database ORM';

  const content = `---
name: database-coder
description: |
  ${orm} database specialist with complete schema knowledge.
  USE WHEN working with database queries, migrations, or data models.
---

# Database Coding Specialist

Expert in ${orm} with knowledge of all project schemas.

## Database Information

**ORM**: ${orm}
${knowledge.databaseSchema?.tables ? `**Tables**: ${knowledge.databaseSchema.tables.length} tables detected` : ''}
${knowledge.databaseSchema?.enums ? `**Enums**: ${knowledge.databaseSchema.enums.length} enums defined` : ''}

## Schema Knowledge

Load \`database-schema.md\` skill for complete schema reference including:
- All table definitions
- Enum values
- Relations between tables

## Query Guidelines

1. **Performance** - All queries must complete in <200ms
2. **Type Safety** - Use ORM's type-safe query builders
3. **Transactions** - Use transactions for multi-step operations
4. **Error Handling** - Handle database errors appropriately

## Instructions

1. **ALWAYS** load \`database-schema.md\` skill first
2. **USE** correct table and enum names from schema
3. **VALIDATE** foreign key relationships
4. **OPTIMIZE** query performance with indexes
5. **TEST** database operations thoroughly

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'database-coder.md'), content);
}

/**
 * Generate API coding agent
 */
async function generateAPICodingAgent(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const routeCount = knowledge.apiRoutes?.length || 0;
  const hasAuth = knowledge.apiRoutes?.some(r => r.auth) || false;

  const content = `---
name: api-coder
description: |
  API development specialist with knowledge of all ${routeCount} existing endpoints.
  USE WHEN implementing or modifying API routes.
---

# API Coding Specialist

Expert in API development following this project's patterns.

## API Information

**Total Routes**: ${routeCount}
**Authentication**: ${hasAuth ? 'Required on protected routes' : 'To be determined'}

## Existing Endpoints

Load \`api-reference.md\` skill for complete API documentation.

## API Guidelines

1. **Response Format** - Consistent JSON responses
2. **Error Handling** - Proper HTTP status codes
3. **Validation** - Input validation for all requests
4. **Performance** - API responses must be <200ms
${hasAuth ? '5. **Authentication** - Verify auth on protected routes' : ''}

## Instructions

1. **ALWAYS** load \`api-reference.md\` skill first
2. **FOLLOW** existing API patterns and response formats
3. **VALIDATE** all request inputs
4. **IMPLEMENT** proper error handling
5. **TEST** API endpoints with integration tests

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'api-coder.md'), content);
}

/**
 * Generate test writer agent
 */
async function generateTestWriterAgent(agentsDir: string, knowledge: ExtractedKnowledge): Promise<void> {
  const testFramework = knowledge.techStack.testing?.[0]?.framework || 'testing framework';

  const content = `---
name: test-writer
description: |
  Testing specialist using ${testFramework}.
  USE WHEN writing tests or improving test coverage.
---

# Test Writing Specialist

Expert in ${testFramework} with knowledge of project testing patterns.

## Testing Framework

**Framework**: ${testFramework}
**Coverage Target**: >95%

## Test Categories

1. **Unit Tests** - Individual functions and methods
2. **Integration Tests** - API endpoints and services
3. **E2E Tests** - User workflows
4. **Edge Cases** - Error conditions and boundaries

## Test Guidelines

1. **Coverage** - Minimum 95% for new code
2. **Assertions** - Multiple assertions per test
3. **Mocking** - Mock external dependencies
4. **Naming** - Clear, descriptive test names
5. **Organization** - Group related tests

## Instructions

1. **ALWAYS** load \`code-patterns.md\` for code structure
2. **WRITE** tests BEFORE implementation (TDD when possible)
3. **COVER** expected cases, edge cases, and failures
4. **VALIDATE** test coverage meets requirements
5. **MAINTAIN** fast test execution

---

**Auto-generated by PAI Knowledge Extractor**
`;

  writeFileSync(join(agentsDir, 'test-writer.md'), content);
}
